In [1]:
import matplotlib.pyplot as plt
import keras

from keras.datasets import mnist

Using TensorFlow backend.


In [2]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()


In [3]:
train_images = train_images.reshape(train_images.shape[0],28*28)
test_images = test_images.reshape(test_images.shape[0],28*28)

train_images = train_images.astype('float32') / 255
test_images = test_images.astype('float32') / 255

In [4]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score

In [5]:
%%time

clf = SGDClassifier(loss='log')
clf.fit(train_images, train_labels)

CPU times: user 49.4 s, sys: 492 ms, total: 49.9 s
Wall time: 49.9 s


In [6]:
from keras import models
from keras import layers

In [7]:
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
network.add(layers.Dense(10, activation='softmax'))

In [8]:
network.compile(optimizer='rmsprop',
               loss='categorical_crossentropy',
               metrics=['accuracy'])

In [9]:
from keras.utils import to_categorical

In [10]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [11]:
%%time

network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 43s - loss: 0.2565 - acc: 0.9254    
Epoch 2/5
60000/60000 [==============================] - 46s - loss: 0.1037 - acc: 0.9685    
Epoch 3/5
60000/60000 [==============================] - 39s - loss: 0.0676 - acc: 0.9797    
Epoch 4/5
60000/60000 [==============================] - 37s - loss: 0.0500 - acc: 0.9850    
Epoch 5/5
60000/60000 [==============================] - 33s - loss: 0.0377 - acc: 0.9888    
CPU times: user 4min 32s, sys: 24.4 s, total: 4min 56s
Wall time: 3min 22s


In [12]:
from scipy import misc
number_2 = misc.imread('2.png')
type(number_2)      


numpy.ndarray

In [13]:
number_2 = number_2.reshape(1,28 *28 )

In [14]:
result_array = network.predict(number_2)
result_array

array([[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [15]:
result_array_prop = network.predict_proba(number_2)
result_array_prop

1/1 [==============================] - 0s


array([[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [16]:
result_class = network.predict_classes(number_2)
result_class

1/1 [==============================] - 0s


array([2])